### PR TITLE
Update to BinaryProvider and add dependency on `Ogg.jl`

### PR DESCRIPTION
**Pull request by staticfloat**
This gives us a much easier install path.  It depends on `Ogg 0.1.0` being merged, which is happening here: https://github.com/JuliaLang/METADATA.jl/pull/14403

### CODE REVIEW

**Comment by staticfloat** [comment]
Just so you know I have been debugging problems with this on FreeBSD, so I will probably need to make some more changes soon.

**Comment by staticfloat** [comment]
Should have put a WIP, my bad.

**Comment by dmbates** [comment]
@staticfloat Would it work better if I transferred ownership of this repository to a Github organization or to you personally?  I am not actually using this package at present and it seems that all the development work on this is being done by you.

**Comment by staticfloat** [comment]
Sure, or if you like you can add me as a collaborator (I suppose all I need access for is pushing commits, managing linked apps like attobot and tagging releases)

**Comment by dmbates** [comment]
You already are a collaborator for pushing commits.  I'll check to see if there is more I should do to enable attobot and tagging.

**Pull request merged**
